blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/onosendae/vibe-devtools/discussions
    about: Perguntas, ideias e discussões gerais
  - name: 📚 Documentação
    url: https://github.com/onosendae/vibe-devtools#readme
    about: Leia a documentação completa
  - name: 📦 npm Registry
    url: https://www.npmjs.com/org/vibe-devtools
    about: Ver packages publicados

