-- Migration: [MIGRATION_DESCRIPTION]
-- Version: [VERSION_NUMBER]
-- Date: [MIGRATION_DATE]

CREATE TABLE IF NOT EXISTS [TABLE_NAME] (
    id BIGSERIAL PRIMARY KEY,
    [COLUMN_NAME] [COLUMN_TYPE] [CONSTRAINTS],
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(255),
    updated_by VARCHAR(255)
);

CREATE INDEX idx_[TABLE_NAME]_[COLUMN_NAME] ON [TABLE_NAME]([COLUMN_NAME]);

COMMENT ON TABLE [TABLE_NAME] IS '[TABLE_DESCRIPTION]';
COMMENT ON COLUMN [TABLE_NAME].[COLUMN_NAME] IS '[COLUMN_DESCRIPTION]';

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_[TABLE_NAME]_updated_at 
    BEFORE UPDATE ON [TABLE_NAME]
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

