name: ⚠️ DEPRECATED - Publish CLI via Tags (Use Changesets)

on:
  push:
    tags:
      - 'cli/v*'
  workflow_dispatch:

jobs:
  publish-cli:
    if: github.repository == 'OnoSendae/vibe-devtools'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: |
          cd apps/cli
          npm ci

      - name: Build CLI
        run: |
          cd apps/cli
          npm run build

      - name: Publish to NPM
        run: |
          cd apps/cli
          npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

