name: ⚠️ DEPRECATED - Publish Packages via Tags (Use Changesets)

on:
  push:
    tags:
      - 'packages/**/v*'
  workflow_dispatch:
    inputs:
      package:
        description: 'Package to publish (basic, research, podcast, content, or all)'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - basic
          - research
          - podcast
          - content

jobs:
  publish-basic:
    if: (github.event.inputs.package == 'basic' || github.event.inputs.package == 'all' || startsWith(github.ref, 'refs/tags/packages/basic/')) && github.repository == 'OnoSendae/vibe-devtools'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Publish @vibe-devtools/basic
        run: |
          cd packages/basic
          npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-research:
    if: (github.event.inputs.package == 'research' || github.event.inputs.package == 'all' || startsWith(github.ref, 'refs/tags/packages/research/')) && github.repository == 'OnoSendae/vibe-devtools'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Publish @vibe-devtools/research
        run: |
          cd packages/research
          npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-podcast:
    if: github.event.inputs.package == 'podcast' || github.event.inputs.package == 'all' || startsWith(github.ref, 'refs/tags/packages/podcast/')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Publish @vibe-devtools/podcast
        run: |
          cd packages/podcast
          npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        continue-on-error: true

  publish-content:
    if: github.event.inputs.package == 'content' || github.event.inputs.package == 'all' || startsWith(github.ref, 'refs/tags/packages/content/')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Publish @vibe-devtools/content
        run: |
          cd packages/content
          npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        continue-on-error: true

